---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .PVName }}
  labels:
    app.kubernetes.io/managed-by: solo-provisioner
    app.kubernetes.io/component: block-node-storage
    app.kubernetes.io/instance: {{ or .Release "block-node" }}
spec:
  claimRef:
    name: {{ .PVCName }}
    namespace: {{ or .Namespace "block-node" }}
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ or .Size "5Gi" }}
  hostPath:
    path: {{ .Path }}
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .PVCName }}
  namespace: {{ or .Namespace "block-node" }}
  labels:
    app.kubernetes.io/managed-by: solo-provisioner
    app.kubernetes.io/component: block-node-storage
    app.kubernetes.io/instance: {{ or .Release "block-node" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ or .Size "5Gi" }}
  volumeName: {{ .PVName }}

