# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 5
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore"
      prefix-development: "build"
      include: "scope"
    open-pull-requests-limit: 5
    groups:
      kubernetes:
        patterns:
          - "k8s.io/api"
          - "k8s.io/apimachinery"
          - "k8s.io/client-go"
          - "k8s.io/apiextensions-apiserver"
          - "k8s.io/apiserver"
          - "k8s.io/cli-runtime"
          - "k8s.io/component-base"
          - "k8s.io/kubectl"
