version: 3
silent: false
output: prefixed
vars:
  OS: [ linux, darwin ]
  ARCH: [ amd64, arm64 ]
  GO_VERSION: 1.24.3
  LDFLAGS: "-w -s"
tasks:
  clean:
    cmds:
      - "rm -rf bin"
      - "rm -f unit-test-report.md"
      - "mkdir -p bin"
      - "go clean -cache -testcache"

  vendor:
    cmds:
      - "go mod vendor"

  lint:
    cmds:
      - "go fmt -x ./..."

  lint:check:
    cmds:
      - "R=$(go fmt ./...) && if [[ -n \"$R\" ]]; then echo \"The following files require formatting:\"; echo \"$R\"; exit 1; fi"

  build:
    deps:
      - "vendor"
    cmds:
      - task: "clean"
      - task: "generate"
      - task: "build:provisioner:all"
    sources:
      - "**/*.go"
    generates:
      - "bin/provisioner-linux-*"
      - "bin/provisioner-darwin-*"

  hash:
    deps:
      - "build"
    cmds:
      - task: "hash:provisioner:all"
    sources:
      - "bin/provisioner-linux-*"
      - "bin/provisioner-darwin-*"
    generates:
      - "bin/*.sha256"

  sign:
    deps:
      - "build"
    cmds:
      - task: "sign:provisioner:all"

  build:image:
    deps:
      - task: "hash"
    cmds:
      - "docker build -t solo-provisioner ."

  generate:
    cmds:
      - "go generate ./..."

  build:provisioner:all:
    desc: "Build the binary for all configured operating systems and architectures"
    cmds:
      - task: build:provisioner:all:os

  build:provisioner:all:os:
    internal: true
    desc: "Build the binary for all configured operating systems"
    cmds:
      - for:
          var: OS
        task: build:provisioner:all:arch
        vars:
          GOOS: "{{.ITEM}}"

  build:provisioner:all:arch:
    internal: true
    desc: "Build the binary for all configured architectures"
    cmds:
      - for:
          var: ARCH
        task: build:provisioner
        vars:
          GOOS: "{{.GOOS}}"
          GOARCH: "{{.ITEM}}"

  build:provisioner:
    internal: true
    desc: "Build the binary for the specified operating system and architecture"
    env:
      GOOS: "{{coalesce .GOOS OS}}"
      GOARCH: "{{coalesce .GOARCH ARCH}}"
    cmds:
      - cmd: go build -ldflags='{{.LDFLAGS}}' -trimpath -o bin/provisioner-{{coalesce .GOOS OS}}-{{coalesce .GOARCH ARCH}} ./cmd/provisioner
      - cmd: chmod +x bin/provisioner-{{coalesce .GOOS OS}}-{{coalesce .GOARCH ARCH}}

  hash:provisioner:all:
    desc: "Hash the binary binaries for all configured operating systems and architectures"
    cmds:
      - task: hash:provisioner:all:os

  hash:provisioner:all:os:
    internal: true
    desc: "Hash the binary binaries for all configured operating systems"
    cmds:
      - for:
          var: OS
        task: hash:provisioner:all:arch
        vars:
          GOOS: "{{.ITEM}}"

  hash:provisioner:all:arch:
    internal: true
    desc: "Hash the binary binaries for all configured architectures"
    cmds:
      - for:
          var: ARCH
        task: hash:provisioner
        vars:
          GOOS: "{{.GOOS}}"
          GOARCH: "{{.ITEM}}"

  hash:provisioner:
    internal: true
    desc: "Hash the binary binaries for the specified operating system and architecture"
    dir: bin
    cmds:
      - cmd: sha256sum provisioner-{{.GOOS}}-{{.GOARCH}} > provisioner-{{.GOOS}}-{{.GOARCH}}.sha256

  sign:provisioner:all:
    desc: "Sign the binary binaries for all configured operating systems and architectures"
    cmds:
      - task: sign:provisioner:all:os

  sign:provisioner:all:os:
    internal: true
    desc: "Sign the binary binaries for all configured operating systems"
    cmds:
      - for:
          var: OS
        task: sign:provisioner:all:arch
        vars:
          GOOS: "{{.ITEM}}"

  sign:provisioner:all:arch:
    internal: true
    desc: "Sign the binary binaries for all configured architectures"
    cmds:
      - for:
          var: ARCH
        task: sign:provisioner
        vars:
          GOOS: "{{.GOOS}}"
          GOARCH: "{{.ITEM}}"

  sign:provisioner:
    internal: true
    desc: "Sign the binary binaries for the specified operating system and architecture"
    env:
      GOOS: "{{coalesce .GOOS OS}}"
      GOARCH: "{{coalesce .GOARCH ARCH}}"
    cmds:
      - task: hash:provisioner
        vars:
          GOOS: "{{.GOOS}}"
          GOARCH: "{{.GOARCH}}"
      - cmd: gpg --batch --yes --armor --output bin/provisioner-{{.GOOS}}-{{.GOARCH}}.sha256.asc --detach-sign bin/provisioner-{{.GOOS}}-{{.GOARCH}}.sha256
      - cmd: gpg --batch --yes --armor --output bin/provisioner-{{.GOOS}}-{{.GOARCH}}.asc --detach-sign bin/provisioner-{{.GOOS}}-{{.GOARCH}}

  test:
    cmds:
      - task: "mocks"
      - task: "test:unit"

  test:unit:
    deps:
      - "generate"
    cmds:
      # Using go-testreport v0.3.2
      - "go install github.com/becheran/go-testreport@90efc1ce13c872f23d6bc8a069527c26288b8f9c"
      - "go test -race -cover -json ./internal/... ./pkg/... ./cmd/... | go-testreport -output unit-test-report.md -vars 'Title:Unit Test Report'"

  test:coverage:
    cmds:
      - "go install github.com/vladopajic/go-test-coverage/v2@7003e902e787e60375e1ce3ae5b85b19313dbff2"
      - "go test -race -cover -json ./internal/... ./pkg/... ./cmd/... -coverprofile=./cover.out -covermode=atomic -coverpkg=./..."
      - "go-test-coverage --config=./.testcoverage.yml"


  run:
    deps:
      - "run:provisioner"

  run:provisioner:
    deps:
      - "build"
    cmds:
      - "bin/provisioner-{{OS}}-{{ARCH}}{{exeExt}} {{.CLI_ARGS}}"

  run:provisioner:skipdl:
    deps:
      - "build"
    env:
      _LOG_LEVEL: "Debug"
    cmds:
      - "bin/provisioner-{{OS}}-{{ARCH}}{{exeExt}} {{.CLI_ARGS}}"

  install:go:
    deps:
      - "install:go:linux"

  install:go:linux:
    internal: true
    status:
      - "command -v go"
    platforms:
      - "linux/amd64"
      - "linux/arm64"
    cmds:
      - "curl -sSLO https://go.dev/dl/go{{.GO_VERSION}}.{{OS}}-{{ARCH}}.tar.gz"
      - "sudo mkdir -p /usr/local/go"
      - "sudo tar -C /usr/local -xzf go{{.GO_VERSION}}.{{OS}}-{{ARCH}}.tar.gz"
      - "rm -f go{{.GO_VERSION}}.{{OS}}-{{ARCH}}.tar.gz"
      - "echo 'PATH=\"${PATH}:/usr/local/go/bin\"' | sudo tee /etc/profile.d/go.sh >/dev/null 2>&1"
      - "source /etc/profile.d/go.sh"
    generates:
      - "/usr/local/go/**"

  mocks:
    cmds:
      - go install github.com/golang/mock/mockgen@v1.6.0
      # Generate mocks in the package it belongs. Note these generated mock files are not checked in.
      - mockgen -source=pkg/plock/plock_api.go -self_package golang.hedera.com/solo-provisioner/pkg/plock -package plock > pkg/plock/mocks_generated.go
      - mockgen -source=pkg/security/principal/principal.go -self_package golang.hedera.com/solo-provisioner/pkg/security/principal -package principal > pkg/security/principal/mocks_generated.go
      - mockgen -source=pkg/detect/detect.go -self_package golang.hedera.com/solo-provisioner/pkg/detect -package detect > pkg/detect/mocks_generated.go
      - mockgen -source=pkg/fsx/fs.go -self_package golang.hedera.com/solo-provisioner/pkg/fsx -package fsx > pkg/fsx/mocks_generated.go
