version: 3
silent: false
output: prefixed
vars:
  OS: [ linux, darwin ]
  ARCH: [ amd64, arm64 ]
  GO_VERSION: 1.24.3
  LDFLAGS: "-w -s"
tasks:
  clean:
    cmds:
      - "rm -rf bin"
      - "rm -f unit-test-report.md"
      - "mkdir -p bin"
      - "go clean -cache -testcache"

  vendor:
    cmds:
      - "go mod vendor"

  lint:
    cmds:
      - "go fmt -x ./..."

  lint:check:
    cmds:
      - "R=$(go fmt ./...) && if [[ -n \"$R\" ]]; then echo \"The following files require formatting:\"; echo \"$R\"; exit 1; fi"

  build:
    deps:
      - "vendor"
    cmds:
      - task: "clean"
      - task: "generate"
      - task: "build:provisioner:all"
    sources:
      - "**/*.go"
    generates:
      - "bin/provisioner-linux-*"
      - "bin/provisioner-darwin-*"

  hash:
    deps:
      - "build"
    cmds:
      - task: "hash:provisioner:all"
    sources:
      - "bin/provisioner-linux-*"
      - "bin/provisioner-darwin-*"
    generates:
      - "bin/*.sha256"

  sign:
    deps:
      - "build"
    cmds:
      - task: "sign:provisioner:all"

  build:image:
    deps:
      - task: "hash"
    cmds:
      - "docker build -t solo-provisioner ."

  generate:
    cmds:
      - "go generate ./..."

  build:provisioner:all:
    desc: "Build the binary for all configured operating systems and architectures"
    cmds:
      - task: build:provisioner:all:os

  build:provisioner:all:os:
    internal: true
    desc: "Build the binary for all configured operating systems"
    cmds:
      - for:
          var: OS
        task: build:provisioner:all:arch
        vars:
          GOOS: "{{.ITEM}}"

  build:provisioner:all:arch:
    internal: true
    desc: "Build the binary for all configured architectures"
    cmds:
      - for:
          var: ARCH
        task: build:provisioner
        vars:
          GOOS: "{{.GOOS}}"
          GOARCH: "{{.ITEM}}"

  build:provisioner:
    internal: true
    desc: "Build the binary for the specified operating system and architecture"
    env:
      GOOS: "{{coalesce .GOOS OS}}"
      GOARCH: "{{coalesce .GOARCH ARCH}}"
    cmds:
      - cmd: go build -ldflags='{{.LDFLAGS}}' -trimpath -o bin/provisioner-{{coalesce .GOOS OS}}-{{coalesce .GOARCH ARCH}} ./cmd/provisioner
      - cmd: chmod +x bin/provisioner-{{coalesce .GOOS OS}}-{{coalesce .GOARCH ARCH}}

  hash:provisioner:all:
    desc: "Hash the binary binaries for all configured operating systems and architectures"
    cmds:
      - task: hash:provisioner:all:os

  hash:provisioner:all:os:
    internal: true
    desc: "Hash the binary binaries for all configured operating systems"
    cmds:
      - for:
          var: OS
        task: hash:provisioner:all:arch
        vars:
          GOOS: "{{.ITEM}}"

  hash:provisioner:all:arch:
    internal: true
    desc: "Hash the binary binaries for all configured architectures"
    cmds:
      - for:
          var: ARCH
        task: hash:provisioner
        vars:
          GOOS: "{{.GOOS}}"
          GOARCH: "{{.ITEM}}"

  hash:provisioner:
    internal: true
    desc: "Hash the binary binaries for the specified operating system and architecture"
    dir: bin
    cmds:
      - cmd: sha256sum provisioner-{{.GOOS}}-{{.GOARCH}} > provisioner-{{.GOOS}}-{{.GOARCH}}.sha256

  sign:provisioner:all:
    desc: "Sign the binary binaries for all configured operating systems and architectures"
    cmds:
      - task: sign:provisioner:all:os

  sign:provisioner:all:os:
    internal: true
    desc: "Sign the binary binaries for all configured operating systems"
    cmds:
      - for:
          var: OS
        task: sign:provisioner:all:arch
        vars:
          GOOS: "{{.ITEM}}"

  sign:provisioner:all:arch:
    internal: true
    desc: "Sign the binary binaries for all configured architectures"
    cmds:
      - for:
          var: ARCH
        task: sign:provisioner
        vars:
          GOOS: "{{.GOOS}}"
          GOARCH: "{{.ITEM}}"

  sign:provisioner:
    internal: true
    desc: "Sign the binary binaries for the specified operating system and architecture"
    env:
      GOOS: "{{coalesce .GOOS OS}}"
      GOARCH: "{{coalesce .GOARCH ARCH}}"
    cmds:
      - task: hash:provisioner
        vars:
          GOOS: "{{.GOOS}}"
          GOARCH: "{{.GOARCH}}"
      - cmd: gpg --batch --yes --armor --output bin/provisioner-{{.GOOS}}-{{.GOARCH}}.sha256.asc --detach-sign bin/provisioner-{{.GOOS}}-{{.GOARCH}}.sha256
      - cmd: gpg --batch --yes --armor --output bin/provisioner-{{.GOOS}}-{{.GOARCH}}.asc --detach-sign bin/provisioner-{{.GOOS}}-{{.GOARCH}}

  test:
    cmds:
      - task: "mocks"
      - task: "test:unit"

  test:unit:
    deps:
      - "generate"
    cmds:
      # Using go-testreport v0.3.2
      - "go install github.com/becheran/go-testreport@90efc1ce13c872f23d6bc8a069527c26288b8f9c"
      - "go test -race -cover -json -tags='!integration' ./internal/... ./pkg/... ./cmd/... | go-testreport -output unit-test-report.md -vars 'Title:Unit Test Report'"

  test:coverage:
    cmds:
      - "go install github.com/vladopajic/go-test-coverage/v2@7003e902e787e60375e1ce3ae5b85b19313dbff2"
      - "go test -race -cover -json -tags='!integration' ./internal/... ./pkg/... ./cmd/... -coverprofile=./cover.out -covermode=atomic -coverpkg=./..."
      - "go-test-coverage --config=./.testcoverage.yml"

  test:integration:
    desc: "Run integration tests (includes cluster_test.go)"
    deps:
      - "generate"
    cmds:
      # Using go-testreport v0.3.2
      - "go install github.com/becheran/go-testreport@90efc1ce13c872f23d6bc8a069527c26288b8f9c"
      - "go test -race -cover -json -tags='integration' ./internal/... ./pkg/... ./cmd/... | go-testreport -output integration-test-report.md -vars 'Title:Integration Test Report'"

  test:unit:docker:
    desc: "Run all unit tests in Docker container (useful for testing system-level functionality)"
    dir: build
    cmds:
      - cmd: |
          # Build and start container in background
          docker build -t local/solo-provisioner-local:latest -f Dockerfile.local .
          docker stop solo-provisioner-local 2>/dev/null || true
          docker rm solo-provisioner-local 2>/dev/null || true
          docker run -d --name solo-provisioner-local --privileged --cap-add=ALL \
            -v "/sys/fs/cgroup:/sys/fs/cgroup:rw" \
            -v "$(pwd)"/..:/app \
            --network host \
            local/solo-provisioner-local:latest tail -f /dev/null
          
          # Wait for container to be ready
          sleep 2
          
          # Update package lists and run all unit tests as root inside the container
          docker exec --user root solo-provisioner-local bash -c "
            apt-get update && 
            cd /app && 
            task test:unit
          "

  run:
    deps:
      - "run:provisioner"

  run:provisioner:
    deps:
      - "build"
    cmds:
      - "bin/provisioner-{{OS}}-{{ARCH}}{{exeExt}} {{.CLI_ARGS}}"

  run:provisioner:skipdl:
    deps:
      - "build"
    env:
      _LOG_LEVEL: "Debug"
    cmds:
      - "bin/provisioner-{{OS}}-{{ARCH}}{{exeExt}} {{.CLI_ARGS}}"

  install:go:
    deps:
      - "install:go:linux"

  install:go:linux:
    internal: true
    status:
      - "command -v go"
    platforms:
      - "linux/amd64"
      - "linux/arm64"
    cmds:
      - "curl -sSLO https://go.dev/dl/go{{.GO_VERSION}}.{{OS}}-{{ARCH}}.tar.gz"
      - "sudo mkdir -p /usr/local/go"
      - "sudo tar -C /usr/local -xzf go{{.GO_VERSION}}.{{OS}}-{{ARCH}}.tar.gz"
      - "rm -f go{{.GO_VERSION}}.{{OS}}-{{ARCH}}.tar.gz"
      - "echo 'PATH=\"${PATH}:/usr/local/go/bin\"' | sudo tee /etc/profile.d/go.sh >/dev/null 2>&1"
      - "source /etc/profile.d/go.sh"
    generates:
      - "/usr/local/go/**"

  mocks:
    cmds:
      - go install github.com/golang/mock/mockgen@v1.6.0
      # Generate mocks in the package it belongs. Note these generated mock files are not checked in.
      - mockgen -source=pkg/security/principal/interface.go -self_package golang.hedera.com/solo-provisioner/pkg/security/principal -package principal > pkg/security/principal/mocks_generated.go
      - mockgen -source=pkg/fsx/interface.go -self_package golang.hedera.com/solo-provisioner/pkg/fsx -package fsx > pkg/fsx/mocks_generated.go
      - mockgen -source=pkg/software/interface.go -self_package golang.hedera.com/solo-provisioner/pkg/software -package software> pkg/software/mocks_generated.go

  # Remote debug tasks for Docker container debugging
  debug:remote:
    desc: "Setup debug environment and show available debug commands"
    deps:
      - "debug:remote:setup"
    cmds:
      - |
        echo "ðŸ› Debug environment ready!"
        echo ""
        echo "Available debug commands:"
        echo "  task debug:remote:test -- [package]   # Debug tests (package required)"
        echo "  task debug:remote:app -- [args...]    # Debug provisioner application"
        echo "  task debug:remote:stop                # Stop debug container"
        echo ""

  debug:remote:setup:
    desc: "Setup Docker container for remote debugging"
    dir: build
    cmds:
      - "./debug-setup.sh"

  debug:remote:test:
    desc: "Start remote test debug server in Docker container (specify package with -- ./pkg/name)"
    deps:
      - "debug:remote:setup"
    dir: build
    cmds:
      - "./debug-run.sh test {{.CLI_ARGS}}"

  debug:remote:app:
    desc: "Start remote application debug server in Docker container (pass args with -- after command)"
    deps:
      - "debug:remote:setup"
    dir: build
    cmds:
      - "./debug-run.sh app {{.CLI_ARGS}}"

  debug:remote:stop:
    desc: "Stop remote debug container"
    cmds:
      - "docker stop solo-provisioner-debug 2>/dev/null || true"
