package steps

const (
	UpdateOSStepId         = "update-OS"
	DisableSwapStepId      = "disable-swap"
	RemoveContainerdStepId = "remove-containerd"

	InstallIPTablesStepId  = "install-iptables"
	InstallGnupg2StepId    = "install-gnupg2"
	InstallConntrackStepId = "install-conntrack"
	InstallSoCatStepId     = "install-socat"
	InstallEBTablesStepId  = "install-ebtables"
	InstallNFTablesStepId  = "install-nftables"

	EnableStartNFTablesStepId    = "enable-start-nftables"
	AutoRemovePackagesStepId     = "auto-remove-packages"
	InstallKernelModulesStepId   = "install-kernel-modules"
	ConfigureKernelModulesStepId = "configure-kernel-modules"
	SetupWorkingDirsStepId       = "setup-working-dirs"

	DownloadDaselStepId                  = "download-dasel"
	DownloadCrioStepId                   = "download-crio"
	DownloadKubernetesToolsStepId        = "download-kubernetes-tools"
	DownloadKubeAdmStepId                = "download-kubeadm"
	DownloadKubectlStepId                = "download-kubectl"
	DownloadHelmStepId                   = "download-helm"
	DownloadK9sStepId                    = "download-k9s"
	DownloadKubeletStepId                = "download-kubelet"
	DownloadKubernetesServiceFilesStepId = "download-kubernetes-service-files"
	DownloadCiliumStepId                 = "download-cilium-cli"

	SetupSandboxFoldersStepId = "setup-sandbox-folders"
	SetupBindMountsStepId     = "setup-bind-mounts"

	InstallDaselStepId           = "install-dasel"
	InstallCrioStepId            = "install-crio"
	InstallKubernetesToolsStepId = "install-kubernetes-tools"
	InstallK9sStepId             = "install-k9s"
	InstallHelmStepId            = "install-helm"
	InstallCiliumStepId          = "install-cilium"
	InstallCiliumCNIStepId       = "install-cilium-cni"
	InstallMetalLBStepId         = "install-metallb"

	ConfigureSandboxKubeletSvcStepId   = "configure-kubelet-service"
	ConfigureSandboxCrioStepId         = "configure-sandbox-crio"
	ConfigureSandboxCrioSvcStepId      = "configure-sandbox-crio-service"
	ConfigureSandboxCrioDefaultsStepId = "configure-sandbox-crio-default"
	UpdateCrioConfStepId               = "update-crio-configuration"
	SetupCrioSymlinkStepId             = "setup-crio-symlinks"
	SetupSystemdServiceSymlinksStepId  = "setup-systemd-symlinks"
	EnableStartServicesStepId          = "enable-start-services"
	TorchPriorKubeAdmConfigStepId      = "torch-prior-kubeadm-config"
	SetupKubeAdminConfigStepId         = "setup-kubeadm-configuration"
	SetBashPipeFailModeStepId          = "set-bash-pipefail-mode"
	InitializeKubernetesClusterStepId  = "initialize-kubernetes-cluster"
	ConfigureCiliumCNIStepId           = "configure-cilium-cni"
	EnforceCiliumCNIStepId             = "restart-crio-and-kubelet"
	DeployMetallbConfigStepId          = "deploy-metallb-config"
	CheckClusterHealthStepId           = "check-cluster-health"
	SetupClusterStepId                 = "setup-kubernetes-cluster"
)
