hedera.config.version=0
netty.mode=TEST
hedera.recordStream.logPeriod=1
balances.exportPeriodSecs=400
files.maxSizeKb=2048
hedera.recordStream.compressFilesOnCreation=true
balances.compressOnCreation=true
contracts.maxNumWithHapiSigsAccess=0
autoRenew.targetTypes=
nodes.gossipFqdnRestricted=false
hedera.profiles.active=TEST
staking.periodMins=1
nodes.updateAccountIdAllowed=true
blockStream.streamMode=RECORDS
scheduling.longTermEnabled=false
bootstrap.throttleDefsJson.resource=data/config/genesis-throttles.json
cache.warmThreads=6
