# SPDX-License-Identifier: Apache-2.0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{.ExternalSecretName}}
  namespace: {{.Namespace}}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{.ClusterSecretStoreName}}
    kind: ClusterSecretStore
  target:
    name: {{.SecretsName}}
    creationPolicy: Owner
    template:
      type: Opaque
      engineVersion: v2
      metadata:
        labels:
          app: grafana-alloy
          cluster: {{.ClusterName}}
  data:
{{.SecretDataEntries}}

